package kotlinx.parcelize

import android.os.Parcel

public interface Parceler<T> {
   public abstract fun create(parcel: Parcel): Any {
   }

   public open fun newArray(size: Int): Array<Any> {
   }

   public abstract fun Any.write(parcel: Parcel, flags: Int) {
   }

   // $VF: Class flags could not be determined
   internal class DefaultImpls {
      @JvmStatic
      fun <T> newArray(var0: Parceler<T>, var1: Int): Array<T> {
         throw new NotImplementedError("Generated by Android Extensions automatically");
      }
   }
}
